### ISSUE TITLE
coe

### ISSUE THREAD

**Issue by qbdl** [NewCityLetter/---#2]
可以请问一下，该怎么把多张图片生成一个coe文件的吗？非常感谢

**Comment by NewCityLetter** [comment]
对于图片我是采用的每个单独一个coe，对于音乐我采用的方法是单独生成多个音乐的coe，手动拼成一个，记录每个音乐的coe起始位置然后跳转。相信对于图片也是类似的。希望可以帮到你。

**Comment by qbdl** [comment]
想问问每个current是指一张图片吗？我把current设成定值时oled上只显示了一条红线，可以请教一下这个吗？谢谢

**Comment by NewCityLetter** [comment]
抱歉之前说反了，图片我是装在一个里面的...歌曲是分开的，我的current指的是地址偏移量，他们的基址都是相同的，基址+当前偏移量就是对应图片

**Comment by qbdl** [comment]
那可以请问一下这个current是0-7指的是不同的图片吗？我采用了coe手动合并后，current设一个定值想查看某一张照片，但是oled屏幕上出现的是一条线，请教一下这个是什么原因呢？

**Comment by NewCityLetter** [comment]
是对应不同的图片。一条线可能是：图片合并错误，检查coe格式/几张图片没有用相同的偏移量/读取地址错误 等。我记得我当初也遇到了这个问题，建议先单独建立项目调试OLED，一张一张图片单独测试，要是还有问题就仔细阅读OLED协议，可能的原因很多。

**Comment by qbdl** [comment]
可以借用一下您的coe文件测试一下我的oled吗？

**Comment by NewCityLetter** [comment]
已上传，慎用

**Comment by qbdl** [comment]
oled是可以的，应该是我的coe文件出了问题，可以请问一下coe文件是用什么生成的吗？我用matlab程序转换但是生成的格式跟一行1536并不兼容，放不进IP核里，所以想请教一下您的coe生成是怎么做的呢？感谢

**Comment by NewCityLetter** [comment]
我当时是找的一个将图片转化成mif格式的，mif格式只需要加上文件头就变成coe格式了

**Comment by qbdl** [comment]
可以方便告诉一下软件吗？我找到的说ps，但我实际操作发现并不行

**Comment by NewCityLetter** [comment]
当时找的BampToMif，应该是这个名字

**Comment by qbdl** [comment]
好像并不行，
![image](https://user-images.githubusercontent.com/87576194/148568583-39c3c7af-2fb0-4e9e-9133-5266b7d5b188.png)
生成的是这种，显然不符合格式

**Comment by qbdl** [comment]
或者请问一下您能帮忙转换一下jpg文件吗？我这边文件转换不适配，一直不成功，用了好多软件，但似乎都是不匹配

**Comment by NewCityLetter** [comment]
上图的这种写个cpp把前面的东西去掉再加个文件头（认真看下coe格式）就可以，我上传了一个转mif的软件，自己尝试吧。有什么具体问题或许可以问问室友或者同学，毕竟这个是我一年前的设计了，很多东西记不太清了。希望能帮到你，有缘再会。
