### ISSUE TITLE
对于图片我是采用的每个单独一个coe，对于音乐我采用的方法是单独生成多个音乐的coe，手动拼成一个，记录每个音乐的coe起始位置然后跳转。相信对于图片也是类似的。希望可以帮到你。

### ISSUE THREAD

**Issue by qbdl** [NewCityLetter/---#3]
对于图片我是采用的每个单独一个coe，对于音乐我采用的方法是单独生成多个音乐的coe，手动拼成一个，记录每个音乐的coe起始位置然后跳转。相信对于图片也是类似的。希望可以帮到你。

_Originally posted by @NewCityLetter in https://github.com/NewCityLetter/Digital-Logic----Electric-Piano/issues/2#issuecomment-1007345571_

**Comment by Rayray-S** [comment]
您好，请问怎么将音乐转换成coe文件呢？又怎么拼到一起呢？/(ㄒoㄒ)/~~

**Comment by NewCityLetter** [comment]
> 您好，请问怎么将音乐转换成coe文件呢？又怎么拼到一起呢？/(ㄒoㄒ)/~~

用软件转化成coe文件之后将中间拼接的文件的文件头尾删除，只保留单独文件头和文件尾即可
